### ISSUE TITLE
i can't in gitpod

### ISSUE THREAD

**Issue by ershedu** [mikiw/ReactJsWalletIntegration#3]
i can't in gitpod

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/workspace/ReactJsWalletIntegration/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspace/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:417:16)
    at /workspace/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:452:10
    at /workspace/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:323:13
    at /workspace/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /workspace/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/workspace/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /workspace/ReactJsWalletIntegration/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by suenot** [comment]
the same error in macos in node 18
```
npm run start
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/suenot/work_hakathon/ReactJsWalletIntegration/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.18.2
```
